# ITC 300 — Data Visualization
## Week 2, Part 1: Python Variables and Exploratory Data Analysis

This notebook develops the Python foundations required for data analysis and then applies them to a real dataset using **pandas**.

### Lab structure
1. **Section 1 — Variables in Python:** storing, naming, and assigning values.
2. **Section 2 — Exploratory Data Analysis:** importing, inspecting, and summarizing a DataFrame.

> **How to use this notebook:** Run the cells in order. Before executing prediction activities, pause and write down the output you expect.

## Section 1 — Learning Objectives

By the end of this section, you will be able to:

- Explain why variables are needed in a program.
- Describe how Python associates variable names with values.
- Declare and initialize variables using the assignment operator (`=`).
- Identify the main Python data types used in the examples.
- Explain Python's dynamic typing behavior.
- Assign one value to several variables.
- Assign different values to several variables in one statement.

## Section 1 — Outline

1. Why variables are needed
2. Declaration and initialization
3. Main Python variable types
4. Dynamic typing
5. Assigning one value to multiple variables
6. Assigning different values to multiple variables
7. Practice exercises

## 1. Why Do We Need Variables?

A variable gives a meaningful name to a value. Instead of repeating a literal value throughout a program, we store it once and refer to it by name. This makes the code easier to read, update, and reuse.

### Comparing Repeated Values with Variables

First, observe a version that repeats the literal value `25`. If that value changes, every occurrence must be edited manually.

In [114]:
#Manipulating values without variables

print(25)
print(25+5)
print(25 * 2)

25
30
50

Now store the value once in `age`. Updating `age` automatically affects every later expression that uses the variable.

In [112]:
# Manipulating values with variables
age = 25
age = 25

print(age)
print(age + 5)
print(age * 2)

25
30
50

## 2. Declaring and Initializing Variables

Python does not require a separate declaration statement. A variable is created when a value is assigned to a name.

```python
variable_name = value
```

The `=` symbol is the **assignment operator**: it associates the name on the left with the value on the right.

### Examples from Different Problem Domains

The following variables represent student information, a bank balance, weather data, and a game state. Notice that the names communicate the purpose of each stored value.

In [5]:
# Examples of Declaring and Initialization of Variables

# Student information
name = "Alice"
age = 22
height = 1.65
graduated = False

# Bank account
account_holder = "John Smith"
account_balance = 1500.75
account_number = 100234
is_active = True

# Weather
city = "Bangkok"
temperature = 32.5
is_raining = False

# Game
player_name = "Hero"
level = 3
score = 250
game_over = False

print(name, age, height, graduated)
print(account_holder, account_balance, account_number, is_active)
print(city, temperature, is_raining)
print(player_name, level, score, game_over)

Alice 22 1.65 False
John Smith 1500.75 100234 True
Bangkok 32.5 False
Hero 3 250 False

## 3. Main Types of Python Variables

Python determines a value's type automatically.

| Type | Purpose | Example |
|---|---|---|
| `str` | Text | `"Maria"` |
| `int` | Whole numbers | `22` |
| `float` | Decimal numbers | `1.65` |
| `bool` | Logical values | `True`, `False` |

Use `type(value)` to check the type currently associated with a value.

### Example 3 — Inspecting Four Basic Types

Run the cell and compare each value with the type reported by Python.

In [7]:
# Example 3:
# Reusing the student information variables declared above

print(type(name))
print(type(age))
print(type(height))
print(type(graduated))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

### Example 4 — Predict the Output

Before running the cell, decide how `15`, `15.0`, and `"15"` differ. Their appearance is similar, but their types are not.

In [9]:
# Example 4: Predict the output.
x = 15
y = 15.0
z = "15"

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'str'>

### Example 5 — Identify Each Type

Classify the city, temperature, and weather-condition variables, then verify your answers with `type()`.

In [11]:
# Example 5: Identify the type of each variable.
# Reusing the weather variables declared above


print(type(city))
print(type(temperature))
print(type(is_raining))

<class 'str'>
<class 'float'>
<class 'bool'>

### 3.1 Python Uses Dynamic Typing

Python is **dynamically typed**. A variable name may refer to values of different types at different moments during execution. The type belongs to the current value, not permanently to the variable name.

### Example 6 — Reassignment and Case Sensitivity

This cell demonstrates two ideas: a variable can be reassigned to a value of another type, and Python treats `Name` and `name` as different identifiers.

In [15]:
# Example 6: Dynamic type changing.
Name = "Alice"
name = "Bob"

print(type(15))
print(type(name))
print(Name)
print(name)

<class 'int'>
<class 'str'>
Alice
Bob

## 4. Assigning One Value to Multiple Variables

**Chain assignment** assigns the same value to several variable names in one statement.

```python
x = y = z = 100
```

This is useful when several settings or counters must begin with the same value.

### Example 7 — Chain Assignment

All three names receive the value `100`. Print them separately to verify the assignment.

In [16]:
# Example - 7: Assigning a Single Value to Multiple Variables
x = y = z = 100

print(x)
print(y)
print(z)

100
100
100

### Example 8 — Practical Chain Assignment

Chain assignment is convenient when several scores or counters begin at the same value.

In [17]:
# Example 8: Real-life Examples

#Initialize multiple players scores.
player1_score = player2_score = 0

print("player1_score =", player1_score)
print("player2_score =", player2_score)

#Initialize multiple quizes values.
quiz1 = quiz2 = quiz3 = 0

print("\nquiz1 = ", quiz1)
print("quiz2 = ", quiz2)
print("quiz3 = ", quiz3)

player1_score = 0
player2_score = 0

quiz1 =  0
quiz2 =  0
quiz3 =  0

## 5. Assigning Different Values to Multiple Variables

Python supports **multiple assignment**, also called unpacking. The number of variables on the left must match the number of values on the right.

```python
name, age, grade = "John", 20, 90
```

### Example 9 — Unpacking Related Values

Values are assigned from left to right: `"John"` to `name`, `20` to `age`, and `90` to `grade`.

In [18]:
# Example 9: Assigning Different Values to Multiple Variables
name, age, grade = "John", 20, 90

print(name)
print(age)
print(grade)

John
20
90

In [20]:
# Example 10: Assigning Different Values to Multiple Variables
x, y = 5, 10
print(x)
print(y)

5
10

In [21]:
# Example 11: Predict the output
city, country = "Paris", "France"

print("city is ", city)
print("country is ", country)

city is  Paris
country is  France

In [23]:
# Example 12:Predict the output
width, height = 640, 480

print("width =", width)
print("height =", height)

width = 640
height = 480

## 6. Practice Exercises

Complete the following exercises independently. Use descriptive variable names, predict the output first, and then execute your solution to verify it.

**Exercise 1:**

Create variables for your **name**, **age**, **country** and **GPA**.  
Initialize and Print all of them.

In [24]:
# Exercise 1
student_name = "Laila"
student_age = 24
student_country = "French"
student_gpa = 3.8

print("Name:", student_name)
print("Age:", student_age)
print("Country:", student_country)
print("GPA:", student_gpa)

Name: Laila
Age: 24
Country: French
GPA: 3.8

**Exercise 2:**

Store the information for a book you liked the

Book title

Author

Price

Display the stored information.

In [25]:
# Exercise 2
book_title = "The Alchemist"
author = "Paulo Coelho"
price = 14.99

print("Book title:", book_title)
print("Author:", author)
print("Price:", price)

Book title: The Alchemist
Author: Paulo Coelho
Price: 14.99

**Exercise 3:**

Assign one value to three variables and print all variables.

In [26]:
# Exercise 3
a = b = c = "Sunshine"

print(a)
print(b)
print(c)

Sunshine
Sunshine
Sunshine

**Exercise 4:**

Assign different values to x, y and z and calculate x + y + z

In [27]:
# Exercise 4
x, y, z = 10, 14, 20
total = x + y + z

print("x + y + z =", total)

x + y + z = 44

# Section 2 — Exploratory Data Analysis
## Creating and Analyzing a pandas DataFrame

Exploratory Data Analysis (EDA) is the process of inspecting and summarizing a dataset before applying visualization or statistical modeling. The goal is to understand the dataset's structure, data types, values, and basic patterns.

> **Dataset required:** Upload `Salaries.csv` to the Colab session before running the data-import cells. In Colab, select the **Files** icon, choose **Upload**, and select the CSV file.

## Section 2 — Learning Objectives

By the end of this section, you will be able to:

- Import pandas using its standard alias, `pd`.
- Read CSV data and configure important import parameters.
- Preview records using `head()` and `tail()`.
- Identify and interpret common pandas data types.
- Distinguish between DataFrame attributes and methods.
- Inspect a DataFrame's dimensions, labels, and values.
- Calculate descriptive statistics for numeric columns.
- Select reproducible random samples.
- Detect missing values and create a cleaned DataFrame.

## Section 2 — Outline

1. Importing required libraries
2. Reading data with pandas
3. Exploring DataFrame records
4. Inspecting DataFrame data types
5. Working with DataFrame attributes
6. Applying DataFrame methods
7. Summarizing the dataset

## 1. Importing the Required Library

**pandas** is a Python library designed for working with structured and tabular data. The alias `pd` is the standard abbreviation used in pandas code and documentation.

In [28]:
# Importing Required Libraries
import pandas as pd

## 2. Reading Data with pandas

The `pd.read_csv()` function reads a comma-separated file and returns a DataFrame. A **DataFrame** is a two-dimensional structure organized into rows and named columns.

> If Python reports `FileNotFoundError`, confirm that `Salaries.csv` has been uploaded and that the filename, including capitalization, is correct.

### 2.1 Loading the Complete CSV File

Displaying `df` confirms that the file has been converted into a DataFrame. For large datasets, prefer `head()` or `sample()` instead of displaying every row.

In [33]:
#Read csv file
from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_csv("Salaries.csv")
df

Saving Salaries.csv to Salaries.csv

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0             1      Prof          B             19           18  Male  139750
1             2      Prof          B             20           16  Male  173200
2             3  AsstProf          B              4            3  Male   79750
3             4      Prof          B             45           39  Male  115000
4             5      Prof          B             40           41  Male  141500
..          ...       ...        ...            ...          ...   ...     ...
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns]

### 2.2 Fine-Tuning the Import Process

The import parameters control how pandas interprets the source file:

| Parameter | Purpose |
|---|---|
| `sep` | Defines the field separator. |
| `header` | Selects the row containing column names. |
| `usecols` | Loads only the required columns. |
| `dtype` | Assigns explicit column types. |
| `na_values` | Defines values that represent missing data. |
| `nrows` | Limits the number of imported rows. |
| `encoding` | Defines how text characters are decoded. |

In [40]:
#Fine-tune data import porocess
import pandas as pd

df1 = pd.read_csv(
    "Salaries.csv",
    sep=",",
    header=0,
    usecols=["rank", "discipline", "salary"],
    na_values=["NA", ""]
)

df1 = df1.head(100)

df1

         rank discipline  salary
0        Prof          B  139750
1        Prof          B  173200
2    AsstProf          B   79750
3        Prof          B  115000
4        Prof          B  141500
..        ...        ...     ...
95   AsstProf          B   84000
96  AssocProf          B   95611
97       Prof          B  129676
98       Prof          B  102235
99       Prof          B  106689

[100 rows x 3 columns]

## 3. Exploring DataFrame Records

Before performing analysis, preview the data to confirm that it loaded correctly and to understand how rows and columns are organized.

- `head()` returns the first five rows by default.
- `head(n)` returns the first *n* rows.
- `tail()` returns the last five rows by default.
- `tail(n)` returns the last *n* rows.

### 3.1 Previewing the First Five Rows

In [41]:
#List first 5 records
df.head()

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750
3           4      Prof          B             45           39  Male  115000
4           5      Prof          B             40           41  Male  141500

### 3.2 Previewing a Custom Number of Rows

In [42]:
#List first 10 records
df.head(10)

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
0,1,Prof,B,19,18,Male,139750
1,2,Prof,B,20,16,Male,173200
2,3,AsstProf,B,4,3,Male,79750
3,4,Prof,B,45,39,Male,115000
4,5,Prof,B,40,41,Male,141500
5,6,AssocProf,B,6,6,Male,97000
6,7,Prof,B,30,23,Male,175000
7,8,Prof,B,45,45,Male,147765
8,9,Prof,B,21,20,Male,119250
9,10,Prof,B,18,18,Female,129000

### 3.3 Inspecting the Last Five Rows

In [43]:
#List last 5 records
df.tail()

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

### 3.4 Inspecting a Custom Number of Final Rows

In [44]:
#List last 7 records
df.tail(7)

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
390         391      Prof          A             40           19  Male  166605
391         392      Prof          A             30           19  Male  151292
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

## 4. Inspecting DataFrame Data Types

Data types determine which operations are valid for each column. Numeric columns support calculations, while text or categorical columns are commonly used for grouping and labeling.

- `df.dtypes` reports the type of every column.
- `df['column'].dtype` reports the type of one selected column.

### 4.1 Data Types of All Columns

In [45]:
#Check types for all the columns
df.dtypes

Unnamed: 0        int64
rank             object
discipline       object
yrs.since.phd     int64
yrs.service       int64
sex              object
salary            int64
dtype: object

### 4.2 Data Type of One Column

In [46]:
#Check a particular column type
df['salary'].dtype

dtype('int64')

## 5. Working with DataFrame Attributes

An **attribute** stores information about an object and is accessed **without parentheses**.

```python
df.shape
df.columns
```

The following attributes describe the DataFrame's types, labels, dimensionality, size, shape, and underlying values.

### 5.1 Column Data Types

In [61]:
#The data type of every column
print(df.dtypes)

Unnamed: 0        int64
rank             object
discipline       object
yrs.since.phd     int64
yrs.service       int64
sex              object
salary            int64
dtype: object

### 5.2 Column Names

In [51]:
#The names of the DataFrame columns
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

### 5.3 Row and Column Axes

In [52]:
#The row labels and column labels
df.axes

[RangeIndex(start=0, stop=397, step=1),
 Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
        'sex', 'salary'],
       dtype='object')]

### 5.4 Number of Dimensions

In [53]:
#The number of dimensions of the DataFrame
df.ndim

#A DataFrame is two-dimensional because it contains rows and columns

2

### 5.5 Total Number of Values

In [54]:
#The total number of values in the DataFrame
df.size

#There are 397 rows and 7 columns, giving a total of 2779 values

2779

### 5.6 DataFrame Shape

In [55]:
#The number of rows and columns
df.shape

#It returns a tuple containing the number of rows and columns

(397, 7)

#### Accessing Row and Column Counts Separately

In [56]:
# Accessing Row and Column Counts Separately
num_rows, num_cols = df.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 397
Number of columns: 7

### 5.7 Underlying Values

In [60]:
#The DataFrame data as a NumPy array

#Because the complete dataset is large, lets display the first three rows
print(df.head(3).to_numpy())

[[1 'Prof' 'B' 19 18 'Male' 139750]
 [2 'Prof' 'B' 20 16 'Male' 173200]
 [3 'AsstProf' 'B' 4 3 'Male' 79750]]

## 6. Applying DataFrame Methods

A **method** performs an operation and is called **with parentheses**.

```python
df.describe()
df.sample(3)
```

The next examples summarize numeric and categorical columns, calculate descriptive statistics, sample observations, and handle missing data.

### 6.1 Reloading the Dataset with an Index Column

In [62]:
df = pd.read_csv("Salaries.csv", index_col=0)
df

         rank discipline  yrs.since.phd  yrs.service   sex  salary
1        Prof          B             19           18  Male  139750
2        Prof          B             20           16  Male  173200
3    AsstProf          B              4            3  Male   79750
4        Prof          B             45           39  Male  115000
5        Prof          B             40           41  Male  141500
..        ...        ...            ...          ...   ...     ...
393      Prof          A             33           30  Male  103106
394      Prof          A             31           19  Male  150564
395      Prof          A             42           25  Male  101738
396      Prof          A             25           15  Male   95329
397  AsstProf          A              8            4  Male   81035

[397 rows x 6 columns]

#### Why `index_col=0` Matters

Setting `index_col=0` tells pandas to use the first CSV column as row labels. This is useful when the file contains a previously saved index column such as `Unnamed: 0` that should not be analyzed as a feature.

### 6.2 Summary Statistics for Numeric Columns

In [63]:
#The describe() method summarizes the numerical columns
df.describe()

       yrs.since.phd  yrs.service         salary
count     397.000000   397.000000     397.000000
mean       22.314861    17.614610  113706.458438
std        12.887003    13.006024   30289.038695
min         1.000000     0.000000   57800.000000
25%        12.000000     7.000000   91000.000000
50%        21.000000    16.000000  107300.000000
75%        32.000000    27.000000  134185.000000
max        56.000000    60.000000  231545.000000

### 6.3 Summary Statistics for All Columns

In [64]:
#To summarize categorical columns as well
df.describe(include='all')

        rank discipline  yrs.since.phd  yrs.service   sex         salary
count    397        397     397.000000   397.000000   397     397.000000
unique     3          2            NaN          NaN     2            NaN
top     Prof          B            NaN          NaN  Male            NaN
freq     266        216            NaN          NaN   358            NaN
mean     NaN        NaN      22.314861    17.614610   NaN  113706.458438
std      NaN        NaN      12.887003    13.006024   NaN   30289.038695
min      NaN        NaN       1.000000     0.000000   NaN   57800.000000
25%      NaN        NaN      12.000000     7.000000   NaN   91000.000000
50%      NaN        NaN      21.000000    16.000000   NaN  107300.000000
75%      NaN        NaN      32.000000    27.000000   NaN  134185.000000
max      NaN        NaN      56.000000    60.000000   NaN  231545.000000

### 6.4 Maximum Values

In [65]:
#Calculate Maximum Values: max()
df.max(numeric_only=True)

yrs.since.phd        56
yrs.service          60
salary           231545
dtype: int64

In [66]:
# Calculate Maximum Value
# of a particular Column
df['salary'].max()

231545

### 6.5 Minimum Values

In [67]:
#Calculate Minimum Values: min()
df.min(numeric_only=True)

yrs.since.phd        1
yrs.service          0
salary           57800
dtype: int64

In [68]:
# Calculate Minimum Value
# of a particular Column
df['salary'].min()

57800

### 6.6 Mean Values

In [69]:
#Calculate Mean Values: mean()
df.mean(numeric_only=True)

yrs.since.phd        22.314861
yrs.service          17.614610
salary           113706.458438
dtype: float64

In [70]:
# Calculate Average Value
# of a particular Column
df['salary'].mean()

np.float64(113706.45843828715)

### 6.7 Median Values

In [71]:
#Calculate Median Values: median()
df.median(numeric_only=True)

yrs.since.phd        21.0
yrs.service          16.0
salary           107300.0
dtype: float64

In [72]:
# Calculate Median Value
# of a particular Column
df['salary'].median()

107300.0

### 6.8 Standard Deviation

In [73]:
#Calculate Standard Deviation: std()
df.std(numeric_only=True)

yrs.since.phd       12.887003
yrs.service         13.006024
salary           30289.038695
dtype: float64

### Interpreting Standard Deviation

Standard deviation measures how widely values are distributed around their mean:

- A **small** standard deviation indicates that values tend to be close to the mean.
- A **large** standard deviation indicates greater variation.

Its unit is the same as the original variable, which makes it easier to interpret alongside the mean.

In [74]:
# Calculate Standard Deviation
# of a particular Column
df['salary'].std()

30289.038694747804

### 6.9 Selecting a Random Sample

In [99]:
#Select a Random Sample: sample()

#The sample(n) method returns n randomly selected rows.
df.sample(3)

          rank discipline  yrs.since.phd  yrs.service   sex  salary
380  AssocProf          A             11            8  Male  104121
60    AsstProf          B              8            3  Male   75044
252       Prof          A             20            8  Male  102000

#### Reproducible Sampling with `random_state`

In [103]:
#For reproducible results, add random_state:
df.sample(3, random_state=42)

         rank discipline  yrs.since.phd  yrs.service     sex  salary
115      Prof          A             12            0  Female  105000
279      Prof          A             24           18    Male  107100
238  AsstProf          A              7            6  Female   63100

### 6.10 Detecting Missing Values

In [104]:
#Remove Rows with Missing Values: dropna()
#Checking the missing values
df.isnull().sum()

rank             0
discipline       0
yrs.since.phd    0
yrs.service      0
sex              0
salary           0
dtype: int64

### 6.11 Removing Rows with Missing Values

In [106]:
#Create a DataFrame without rows
#containing missing values:
df_clean = df.dropna()

#Compare the dimensions:
print("Before:", df.shape)
print("After:", df_clean.shape)

Before: (397, 6)
After: (397, 6)

### Interpreting the Missing-Value Result

The dimensions remain unchanged because this dataset does not contain missing values in the inspected rows. In datasets that contain missing values, `dropna()` removes affected rows by default, so the number of rows may decrease.

---

## Section 2 — Summary

In this section, you:

- Imported and loaded tabular data with pandas.
- Previewed the beginning and end of a DataFrame.
- Inspected column data types and DataFrame attributes.
- Used descriptive methods to calculate summary statistics.
- Selected random samples reproducibly.
- Checked for missing values and created a cleaned DataFrame.

### Reflection questions
1. Why should data types be checked before calculating statistics?
2. What is the difference between `df.shape` and `df.size`?
3. Why is `random_state` useful when sampling rows?
4. When could removing rows with `dropna()` be inappropriate?

**Write down your reflections here:**

My experience of working with pandas in this section was useful in learning the importance of ensuring that data is appropriate for analysis, as well as knowing how to produce results with it. The first noteworthy lesson was to ensure that the data type of the data was checked before calculating statistics. The data types need to be analyzed differently, and the selection of a wrong data type can result in conducting wrong computations or drawing wrong conclusions. Data types might also affect subsequent operations, like graphing, charting and other visualizing. It is therefore important to confirm the structure and nature of the data before getting started and to prevent errors and reliable analysis.

Also I learned something about the distinction between `df.shape` and `df.size`. The shape attribute of the DataFrame returns a tuple of the number of rows and columns. Unlike the previous, `df.size` returns the total number of elements in the DataFrame. It is useful to know this difference when verifying the structure and size of a set of data. If we have a DataFrame with 100 rows and 3 columns, its shape is (100, 3) and its size is 300.

One of the other useful ideas was for sampling data, use `random_state`. Randomness in sampling may occur, so when using `random_state` the results will be reproducible. This results in the possibility of selecting the same sample, if I use the same code with the same random state, or if another researcher uses the same code with the same random state. This is to test, compare, and ensure that there is reliability and ease of data analysis for the data to be reproduced.

Lastly, I discovered that `dropna()` is not always the correct function to use when removing missing values. When there are many missing values in a dataset, deleting all the lines with missing data may cause the loss of a lot of information. It may also cause the remaining data to be less representative of the original population, especially if the missing data are clustered in certain population groups. In other cases, the data could require other cleaning operations, such as checking for missing values, or examining why values are missing.

I learned from these four questions that data preparation is a crucial step in the data analysis process. Understanding the structure, quality and limitations of the data set before doing calculations or creating visualizations.